<a href="https://colab.research.google.com/github/Willi-blip/numpy1/blob/main/Ejercicios_basicos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPY, Libreria de ciencia de datos

In [41]:
import numpy as np
#pip install numpy

ARRAYS DE 1 DIMENSION

In [5]:
array_id=np.array([10,20,30])
print(array_id)

[10 20 30]


In [ ]:
array_id

ARRAYS DE 2 DIMENSIONES

In [6]:
array_2d=np.array([(10,20,30),(40,50,50)])
array_2d

array([[10, 20, 30],
       [40, 50, 50]])

ARRATS DE 3 DIMENSIONES

In [8]:
array_3d=np.array([(10,20,30),(40,50,60),(70,80,90)],dtype=float)
array_3d

array([[10., 20., 30.],
       [40., 50., 60.],
       [70., 80., 90.]])

ARRAY CON 0 DE 3 FILAS 4 CULUMNAS

In [43]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [44]:
print(np.zeros((3,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


ARRAY DE UNOS CON2 DIMENSIONES 4 FILAS 5 COLUMNAS

In [15]:
np.ones([2,4,5])

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

ARRAYS INTERVALOS Y SALTOS

In [18]:
np.arange(11,30,2)

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

ARRAYS CON INTERVALOS Y DIVISIONES

In [26]:
np.linspace(0,4,7)

array([0.        , 0.66666667, 1.33333333, 2.        , 2.66666667,
       3.33333333, 4.        ])

ARRAY CON VALORES DADOS

In [27]:
np.full([3,3],7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

ARRAY MATRIZ IDENTIDAD, DIAGONAL, DE UNOS

In [31]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

ARRAY VALORES ALEATORIOS

In [35]:
np.random.random((4,4))

array([[0.22097647, 0.48595463, 0.40543539, 0.98178174],
       [0.82150092, 0.12912591, 0.20897037, 0.35526123],
       [0.49613813, 0.18105079, 0.60405846, 0.30800038],
       [0.42811414, 0.18479222, 0.55975856, 0.47935327]])

ARRAY NUMEROS VACIOS 4*3

In [45]:
np.empty((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

GRABAR Y CARGAR

In [50]:
#grabar
np.save('mi_array_3d',array_3d)

In [54]:
#cargar
mi_array=np.load('mi_array_3d.npy')
mi_array

array([[10., 20., 30.],
       [40., 50., 60.],
       [70., 80., 90.]])

In [55]:
np.save('mi_array_2d',array_2d)

In [56]:
mi_array=np.load('mi_array_2d.npy')
mi_array

array([[10, 20, 30],
       [40, 50, 50]])

GRABAR Y CARGAR FICHEROS DE TEXTOS

In [57]:
#grabar el fichero de texto
np.savetxt('mi_array.txt',array_2d,delimiter=' ')

In [58]:
#cargar el fichero de texto
np.loadtxt('mi_array.txt')

array([[10., 20., 30.],
       [40., 50., 50.]])

EJECICIOS

In [59]:
asignaturas = ["Matemáticas", "Física", "Química", "Historia", "Lengua"]
asignaturas

['Matemáticas', 'Física', 'Química', 'Historia', 'Lengua']

In [60]:
for asignatura in asignaturas:
    print("Yo estudio " + asignatura)

Yo estudio Matemáticas
Yo estudio Física
Yo estudio Química
Yo estudio Historia
Yo estudio Lengua


In [62]:
notas = []
for asignatura in asignaturas:
  nota = input("¿Qué nota has sacado en {}? ".format(asignatura))
  notas.append(nota)

for i in range(len(asignaturas)):
  print("En {} has sacado: {}".format(asignaturas[i], notas[i]))

¿Qué nota has sacado en Matemáticas? 15
¿Qué nota has sacado en Física? 15
¿Qué nota has sacado en Química? 14
¿Qué nota has sacado en Historia? 13
¿Qué nota has sacado en Lengua? 16
En Matemáticas has sacado: 15
En Física has sacado: 15
En Química has sacado: 14
En Historia has sacado: 13
En Lengua has sacado: 16


In [63]:
numeros_ganadores = []
while len(numeros_ganadores) < 6:
  try:
    numero = int(input(f"Introduce el número {len(numeros_ganadores) + 1} de la lotería: "))
    if 1 <= numero <= 50 and numero not in numeros_ganadores:
      numeros_ganadores.append(numero)
    elif numero in numeros_ganadores:
      print("Ese número ya ha sido introducido. Introduce uno diferente.")
    else:
      print("El número debe estar entre 1 y 50.")
  except ValueError:
    print("Entrada no válida. Por favor, introduce un número entero.")

numeros_ganadores.sort()
print("Los números ganadores de la lotería primitiva son:")
numeros_ganadores


Introduce el número 1 de la lotería: 1
Introduce el número 2 de la lotería: 5
Introduce el número 3 de la lotería: 49
Introduce el número 4 de la lotería: 7
Introduce el número 5 de la lotería: 23
Introduce el número 6 de la lotería: 24
Los números ganadores de la lotería primitiva son:


[1, 5, 7, 23, 24, 49]

In [69]:
numeros = list(range(1, 11))
numeros.reverse()
print(",".join(map(str, numeros)))

1,2,3,4,5,6,7,8,9,10


In [71]:
asignaturas = ["Matemáticas", "Física", "Química", "Historia", "Lengua"]
notas = []
for asignatura in asignaturas:
    while True:
        try:
            nota = float(input(f"¿Qué nota has sacado en {asignatura}? "))
            if 0 <= nota <= 20:
                notas.append(nota)
                break
            else:
                print("Por favor, introduce una nota entre 0 y 10.")
        except ValueError:
            print("Entrada no válida. Por favor, introduce un número para la nota.")

asignaturas_a_repetir = []
for i in range(len(asignaturas)):
    if notas[i] < 10:
        asignaturas_a_repetir.append(asignaturas[i])

if asignaturas_a_repetir:
    print("\nAsignaturas que tienes que repetir:")
    for asignatura in asignaturas_a_repetir:
        print(asignatura)
else:
    print("\n¡Enhorabuena! Has aprobado todas las asignaturas.")

¿Qué nota has sacado en Matemáticas? 9
¿Qué nota has sacado en Física? 15
¿Qué nota has sacado en Química? 15
¿Qué nota has sacado en Historia? 20
¿Qué nota has sacado en Lengua? 8

Asignaturas que tienes que repetir:
Matemáticas
Lengua


In [76]:
alfabeto = list('abcdefghijklmnopqrstuvwxyz')
alfabeto_filtrado = [letra for indice, letra in enumerate(alfabeto) if (indice + 1) % 3 != 0]
alfabeto_filtrado

['a',
 'b',
 'd',
 'e',
 'g',
 'h',
 'j',
 'k',
 'm',
 'n',
 'p',
 'q',
 's',
 't',
 'v',
 'w',
 'y',
 'z']

In [79]:
palabra = input("Introduce una palabra: ")
palabra = palabra.lower().replace(" ", "")
if palabra == palabra[::-1]:
  print("Es un palíndromo.")
else:
  print("No es un palíndromo.")

Introduce una palabra: we
No es un palíndromo.


In [80]:
palabra = input("Introduce una palabra: ").lower()
vocales = {'a': 0, 'e': 0, 'i': 0, 'o': 0, 'u': 0}
for letra in palabra:
  if letra in vocales:
    vocales[letra] += 1
for vocal, count in vocales.items():
  print(f"La vocal '{vocal}' aparece {count} veces.")

Introduce una palabra: palabra
La vocal 'a' aparece 3 veces.
La vocal 'e' aparece 0 veces.
La vocal 'i' aparece 0 veces.
La vocal 'o' aparece 0 veces.
La vocal 'u' aparece 0 veces.
