<a href="https://colab.research.google.com/github/Willi-blip/numpy1/blob/main/Ejercicios_basicos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPY, Libreria de ciencia de datos

In [1]:
import numpy as np
#pip install numpy

ARRAYS DE 1 DIMENSION

In [2]:
array_id=np.array([10,20,30])
print(array_id)

[10 20 30]


In [3]:
array_id

array([10, 20, 30])

ARRAYS DE 2 DIMENSIONES

In [4]:
array_2d=np.array([(10,20,30),(40,50,50)])
array_2d

array([[10, 20, 30],
       [40, 50, 50]])

ARRATS DE 3 DIMENSIONES

In [5]:
array_3d=np.array([(10,20,30),(40,50,60),(70,80,90)],dtype=float)
array_3d

array([[10., 20., 30.],
       [40., 50., 60.],
       [70., 80., 90.]])

ARRAY CON 0 DE 3 FILAS 4 CULUMNAS

In [6]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
print(np.zeros((3,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


ARRAY DE UNOS CON2 DIMENSIONES 4 FILAS 5 COLUMNAS

In [8]:
np.ones([2,4,5])

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

ARRAYS INTERVALOS Y SALTOS

In [9]:
np.arange(11,30,2)

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

ARRAYS CON INTERVALOS Y DIVISIONES

In [10]:
np.linspace(0,4,7)

array([0.        , 0.66666667, 1.33333333, 2.        , 2.66666667,
       3.33333333, 4.        ])

ARRAY CON VALORES DADOS

In [11]:
np.full([3,3],7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

ARRAY MATRIZ IDENTIDAD, DIAGONAL, DE UNOS

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

ARRAY VALORES ALEATORIOS

In [13]:
np.random.random((4,4))

array([[0.18425382, 0.90178719, 0.62392675, 0.14212272],
       [0.04655143, 0.94999285, 0.36152897, 0.49987985],
       [0.2647084 , 0.19224743, 0.33672178, 0.72952267],
       [0.59369492, 0.33665488, 0.8458882 , 0.30919121]])

ARRAY NUMEROS VACIOS 4*3

In [14]:
np.empty((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

GRABAR Y CARGAR

In [15]:
#grabar
np.save('mi_array_3d',array_3d)

In [16]:
#cargar
mi_array=np.load('mi_array_3d.npy')
mi_array

array([[10., 20., 30.],
       [40., 50., 60.],
       [70., 80., 90.]])

In [17]:
np.save('mi_array_2d',array_2d)

In [18]:
mi_array=np.load('mi_array_2d.npy')
mi_array

array([[10, 20, 30],
       [40, 50, 50]])

GRABAR Y CARGAR FICHEROS DE TEXTOS

In [19]:
#grabar el fichero de texto
np.savetxt('mi_array.txt',array_2d,delimiter=' ')

In [20]:
#cargar el fichero de texto
np.loadtxt('mi_array.txt')

array([[10., 20., 30.],
       [40., 50., 50.]])

EJECICIOS PROPUESTO

In [21]:
asignaturas = ["Matemáticas", "Física", "Química", "Historia", "Lengua"]
asignaturas

['Matemáticas', 'Física', 'Química', 'Historia', 'Lengua']

In [22]:
for asignatura in asignaturas:
    print("Yo estudio " + asignatura)

Yo estudio Matemáticas
Yo estudio Física
Yo estudio Química
Yo estudio Historia
Yo estudio Lengua


In [23]:
notas = []
for asignatura in asignaturas:
  nota = input("¿Qué nota has sacado en {}? ".format(asignatura))
  notas.append(nota)

for i in range(len(asignaturas)):
  print("En {} has sacado: {}".format(asignaturas[i], notas[i]))

¿Qué nota has sacado en Matemáticas? 15
¿Qué nota has sacado en Física? 15
¿Qué nota has sacado en Química? 15
¿Qué nota has sacado en Historia? 15
¿Qué nota has sacado en Lengua? 15
En Matemáticas has sacado: 15
En Física has sacado: 15
En Química has sacado: 15
En Historia has sacado: 15
En Lengua has sacado: 15


In [24]:
numeros_ganadores = []
while len(numeros_ganadores) < 6:
  try:
    numero = int(input(f"Introduce el número {len(numeros_ganadores) + 1} de la lotería: "))
    if 1 <= numero <= 50 and numero not in numeros_ganadores:
      numeros_ganadores.append(numero)
    elif numero in numeros_ganadores:
      print("Ese número ya ha sido introducido. Introduce uno diferente.")
    else:
      print("El número debe estar entre 1 y 50.")
  except ValueError:
    print("Entrada no válida. Por favor, introduce un número entero.")

numeros_ganadores.sort()
print("Los números ganadores de la lotería primitiva son:")
numeros_ganadores


Introduce el número 1 de la lotería: 5
Introduce el número 2 de la lotería: 4
Introduce el número 3 de la lotería: 6
Introduce el número 4 de la lotería: 8
Introduce el número 5 de la lotería: 9
Introduce el número 6 de la lotería: 7
Los números ganadores de la lotería primitiva son:


[4, 5, 6, 7, 8, 9]

In [25]:
numeros = list(range(1, 11))
numeros.reverse()
print(",".join(map(str, numeros)))

10,9,8,7,6,5,4,3,2,1


In [26]:
asignaturas = ["Matemáticas", "Física", "Química", "Historia", "Lengua"]
notas = []
for asignatura in asignaturas:
    while True:
        try:
            nota = float(input(f"¿Qué nota has sacado en {asignatura}? "))
            if 0 <= nota <= 20:
                notas.append(nota)
                break
            else:
                print("Por favor, introduce una nota entre 0 y 10.")
        except ValueError:
            print("Entrada no válida. Por favor, introduce un número para la nota.")

asignaturas_a_repetir = []
for i in range(len(asignaturas)):
    if notas[i] < 10:
        asignaturas_a_repetir.append(asignaturas[i])

if asignaturas_a_repetir:
    print("\nAsignaturas que tienes que repetir:")
    for asignatura in asignaturas_a_repetir:
        print(asignatura)
else:
    print("\n¡Enhorabuena! Has aprobado todas las asignaturas.")

¿Qué nota has sacado en Matemáticas? 15
¿Qué nota has sacado en Física? 15
¿Qué nota has sacado en Química? 15
¿Qué nota has sacado en Historia? 15
¿Qué nota has sacado en Lengua? 15

¡Enhorabuena! Has aprobado todas las asignaturas.


In [27]:
alfabeto = list('abcdefghijklmnopqrstuvwxyz')
alfabeto_filtrado = [letra for indice, letra in enumerate(alfabeto) if (indice + 1) % 3 != 0]
alfabeto_filtrado

['a',
 'b',
 'd',
 'e',
 'g',
 'h',
 'j',
 'k',
 'm',
 'n',
 'p',
 'q',
 's',
 't',
 'v',
 'w',
 'y',
 'z']

In [28]:
palabra = input("Introduce una palabra: ")
palabra = palabra.lower().replace(" ", "")
if palabra == palabra[::-1]:
  print("Es un palíndromo.")
else:
  print("No es un palíndromo.")

Introduce una palabra: 15
No es un palíndromo.


In [29]:
palabra = input("Introduce una palabra: ").lower()
vocales = {'a': 0, 'e': 0, 'i': 0, 'o': 0, 'u': 0}
for letra in palabra:
  if letra in vocales:
    vocales[letra] += 1
for vocal, count in vocales.items():
  print(f"La vocal '{vocal}' aparece {count} veces.")

Introduce una palabra: 15
La vocal 'a' aparece 0 veces.
La vocal 'e' aparece 0 veces.
La vocal 'i' aparece 0 veces.
La vocal 'o' aparece 0 veces.
La vocal 'u' aparece 0 veces.


In [30]:
precios = [50, 75, 46, 22, 80, 65, 8]
print("El precio menor es:", min(precios))
print("El precio mayor es:", max(precios))

El precio menor es: 8
El precio mayor es: 80


In [31]:
# Vectores en listas
vector1 = [1, 2, 3]
vector2 = [-1, 0, 2]

# Calcular el producto escalar
producto_escalar = sum(x * y for x, y in zip(vector1, vector2))

# Mostrar el resultado
print(f"El producto escalar de {vector1} y {vector2} es: {producto_escalar}")

El producto escalar de [1, 2, 3] y [-1, 0, 2] es: 5


In [32]:
# Definir las matrices como listas anidadas
matriz1 = [[1, 2],
           [3, 4]]

matriz2 = [[5, 6],
           [7, 8]]

# Almacenar las matrices en una lista
matrices = [matriz1, matriz2]

# Función para multiplicar dos matrices
def multiplicar_matrices(matriz_a, matriz_b):
    # Verificar si la multiplicación es posible
    if len(matriz_a[0]) != len(matriz_b):
        return "No se pueden multiplicar las matrices."

    # Inicializar la matriz resultado con ceros
    filas_a = len(matriz_a)
    columnas_a = len(matriz_a[0])
    filas_b = len(matriz_b)
    columnas_b = len(matriz_b[0])
    matriz_resultado = [[0 for _ in range(columnas_b)] for _ in range(filas_a)]

    # Realizar la multiplicación
    for i in range(filas_a):
        for j in range(columnas_b):
            for k in range(columnas_a):
                matriz_resultado[i][j] += matriz_a[i][k] * matriz_b[k][j]

    return matriz_resultado

# Calcular el producto de las matrices en la lista
if len(matrices) >= 2:
    producto = matrices[0]
    for i in range(1, len(matrices)):
        producto = multiplicar_matrices(producto, matrices[i])
        if isinstance(producto, str): # Verificar si hubo error en la multiplicación
            print(producto)
            break
    else:
        print("El producto de las matrices es:")
        for fila in producto:
            print(fila)
elif len(matrices) == 1:
    print("Solo hay una matriz en la lista:")
    for fila in matrices[0]:
        print(fila)
else:
    print("La lista de matrices está vacía.")

El producto de las matrices es:
[19, 22]
[43, 50]


In [33]:
import numpy as np

entrada = input("Introduce una muestra de números separados por comas: ")
numeros_str = entrada.split(',')
numeros = []
for num_str in numeros_str:
  try:
    numeros.append(float(num_str.strip()))
  except ValueError:
    print(f"Advertencia: '{num_str.strip()}' no es un número válido y será ignorado.")

if numeros:
  muestra = np.array(numeros)
  media = np.mean(muestra)
  desviacion_tipica = np.std(muestra)

  print(f"La muestra es: {numeros}")
  print(f"La media es: {media}")
  print(f"La desviación típica es: {desviacion_tipica}")
else:
  print("No se introdujeron números válidos.")


Introduce una muestra de números separados por comas: 15
La muestra es: [15.0]
La media es: 15.0
La desviación típica es: 0.0


TIPOS DE DATOS

In [34]:
#decimal
np.int64

numpy.int64

In [35]:
#decimal, flotante
np.float64

numpy.float64

In [36]:
#conplejos
np.complex64

numpy.complex64

In [37]:
#foleano
np.bool_

numpy.bool

In [38]:
#objectos
np.object_

numpy.object_

In [39]:
#cadena de datos
np.strings

<module 'numpy.strings' from '/usr/local/lib/python3.11/dist-packages/numpy/strings/__init__.py'>

In [40]:
np.bytes_

numpy.bytes_

PROPIEDADES Y CARACTERISTICAS DE ENTORNOS

In [41]:
array_3d

array([[10., 20., 30.],
       [40., 50., 60.],
       [70., 80., 90.]])

In [49]:
array_3d.strides

(24, 8)

In [43]:
#altitud
len(array_3d)

3

In [52]:
#numero de dimensiones
array_3d.ndim

2

In [67]:
array_5d=np.array(((5,2,1,5,6),(8,4,6,5,5),(2,5,7,4,4),(79,4,5,45,4),(3,7,56,4,5)),dtype=float)
array_5d

array([[ 5.,  2.,  1.,  5.,  6.],
       [ 8.,  4.,  6.,  5.,  5.],
       [ 2.,  5.,  7.,  4.,  4.],
       [79.,  4.,  5., 45.,  4.],
       [ 3.,  7., 56.,  4.,  5.]])

In [68]:
array_5d.ndim

2

In [69]:
#tipos de datos
array_3d.dtype

dtype('float64')

In [70]:
array_3d.dtype.name

'float64'

In [73]:
#combertir de un tipo a otro tipo de dato
array_3d.astype(int)

array([[ 5,  2,  1],
       [ 8,  4,  6],
       [ 2,  5,  7],
       [79,  4,  5],
       [ 3,  7, 56]])

OPERADORES MATEMATICOS

In [76]:
array_id

array([10, 20, 30])

In [81]:
#array de ejemplos
array1=np.random.random([4,4])
array1

array([[0.73922428, 0.52669855, 0.45386683, 0.39330891],
       [0.74878066, 0.75744715, 0.13740936, 0.15349179],
       [0.33093214, 0.16822378, 0.37990037, 0.50602974],
       [0.15646627, 0.95772189, 0.34434353, 0.44163123]])

In [78]:
array2=np.random.random([4,4])
array2

array([[0.1004542 , 0.76957291, 0.18994306, 0.01076079],
       [0.04384188, 0.07164585, 0.97746794, 0.67696134],
       [0.68682925, 0.73681785, 0.74308311, 0.29116623],
       [0.38721042, 0.8896066 , 0.52090105, 0.51000763]])

In [79]:
array3=np.random.random([4,4])
array3

array([[0.6294199 , 0.98655637, 0.18992463, 0.42608031],
       [0.32388282, 0.07185542, 0.63145051, 0.02899946],
       [0.51874884, 0.15427428, 0.04257366, 0.01861475],
       [0.33528741, 0.08185574, 0.52676599, 0.7724645 ]])

In [82]:
#suma
array4=(array1+array2)
array4

array([[0.83967848, 1.29627146, 0.64380989, 0.4040697 ],
       [0.79262254, 0.829093  , 1.11487731, 0.83045313],
       [1.01776139, 0.90504162, 1.12298348, 0.79719597],
       [0.54367669, 1.84732849, 0.86524458, 0.95163886]])

In [84]:
#resta
array4=(array1-array2)
array4

array([[ 0.63877007, -0.24287437,  0.26392377,  0.38254811],
       [ 0.70493877,  0.6858013 , -0.84005858, -0.52346955],
       [-0.3558971 , -0.56859407, -0.36318275,  0.21486351],
       [-0.23074415,  0.06811529, -0.17655752, -0.0683764 ]])

In [87]:
#multiplicar
array4=np.multiply(array1,array2,array3)
array4

array([[0.07425819, 0.40533294, 0.08620885, 0.00423232],
       [0.03282795, 0.05426795, 0.13431325, 0.10390801],
       [0.22729387, 0.12395028, 0.28229755, 0.14733877],
       [0.06058537, 0.85199572, 0.17936891, 0.2252353 ]])

In [88]:
#division
array4=np.divide(array1,array2)
array4

array([[ 7.35881875,  0.6844037 ,  2.38948891, 36.55017421],
       [17.07911769, 10.57210041,  0.14057685,  0.22673642],
       [ 0.48182593,  0.22831121,  0.51124882,  1.73794103],
       [ 0.4040859 ,  1.07656788,  0.66105363,  0.86593063]])

In [89]:
#esponentes
np.exp(array1)

array([[2.09431028, 1.69333262, 1.57438833, 1.48187608],
       [2.11442024, 2.13282448, 1.14729772, 1.16589822],
       [1.39226531, 1.18320135, 1.4621389 , 1.65869267],
       [1.16937132, 2.60575352, 1.41106329, 1.5552421 ]])

In [90]:
#operadores
np.cosh(array1)

array([[1.28589722, 1.14194202, 1.10477782, 1.07834817],
       [1.29368156, 1.30084316, 1.00945553, 1.01180301],
       [1.05525961, 1.01418302, 1.07303423, 1.13078855],
       [1.01226584, 1.49475984, 1.05987436, 1.09911441]])

In [92]:
#longarinmo
np.log(array2)
array2

array([[0.1004542 , 0.76957291, 0.18994306, 0.01076079],
       [0.04384188, 0.07164585, 0.97746794, 0.67696134],
       [0.68682925, 0.73681785, 0.74308311, 0.29116623],
       [0.38721042, 0.8896066 , 0.52090105, 0.51000763]])

COMPARACIONES ENTRE MATRICES

In [93]:
#==
array1==array2

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [94]:
#el menor
array1

array([[0.73922428, 0.52669855, 0.45386683, 0.39330891],
       [0.74878066, 0.75744715, 0.13740936, 0.15349179],
       [0.33093214, 0.16822378, 0.37990037, 0.50602974],
       [0.15646627, 0.95772189, 0.34434353, 0.44163123]])

In [96]:
array1 > 0.5

array([[ True,  True, False, False],
       [ True,  True, False, False],
       [False, False, False,  True],
       [False,  True, False, False]])

In [97]:
#<= o >=
array2

array([[0.1004542 , 0.76957291, 0.18994306, 0.01076079],
       [0.04384188, 0.07164585, 0.97746794, 0.67696134],
       [0.68682925, 0.73681785, 0.74308311, 0.29116623],
       [0.38721042, 0.8896066 , 0.52090105, 0.51000763]])

In [98]:
array2 >= 0.5

array([[False,  True, False, False],
       [False, False,  True,  True],
       [ True,  True,  True, False],
       [False,  True,  True,  True]])

ESTADISTICAS Y FUNCIONES

In [99]:
array6 = np.random.random((5,5))
array6

array([[0.89018316, 0.05277727, 0.18093761, 0.28669465, 0.4354931 ],
       [0.56233716, 0.59094395, 0.95785161, 0.1579927 , 0.71970966],
       [0.17443662, 0.03578542, 0.62595233, 0.12920135, 0.25715608],
       [0.5008651 , 0.33675208, 0.50872247, 0.61747648, 0.28196846],
       [0.89663201, 0.96302458, 0.60573907, 0.89486169, 0.31316645]])

In [100]:
#suma de elementos
sumatotal=array6.sum()
print(sumatotal)

11.976661074036713


In [102]:
#valor minimo y maximo
array6.max()

np.float64(0.963024581166707)

In [106]:
#maximo por fila o columna
array6.max(axis=1)

array([0.89018316, 0.95785161, 0.62595233, 0.61747648, 0.96302458])

In [ ]:
#fila acumulada
array6.cumprod(axis=1)

In [107]:
np.mean(array6)

np.float64(0.4790664429614685)

In [108]:
np.median(array6)

np.float64(0.5008651037892339)

In [109]:
np.std(array6)

np.float64(0.28812328409275384)